### ISSUE TITLE
Support EdDSA sign

### ISSUE THREAD

**Issue by crossle** [appsup-dart/jose#15]
Use ed25519 sign jwt

**Comment by Tougee** [comment]
Hi @rbellens , thanks for the nice library.

About a week ago, I started to support sign and verify of EdDSA on the fork of this repo. In the process, I found that this project is based on appsup-dart/crypto_keys, and crypto_keys is based on pc-dart, so I forked these projects, and made some modifications. Now they are basically usable and cover some tests.

https://github.com/Tougee/jose/pull/1
https://github.com/Tougee/crypto_keys/pull/1

 I hope you can help me review the code when you're free, thanks!

**Comment by rbellens** [comment]
Hi @Tougee 

Thanks for this work.

I guess, we'll have to wait for this to be merged in pc-dart, before being able to release it.

**Comment by heri16** [comment]
@rbellens Now that it has been merged, any intent to release this?
