### ISSUE TITLE
A256 Web algorithm is not working

### ISSUE THREAD

**Issue by mikhailbabenkov** [appsup-dart/jose#20]
![image](https://user-images.githubusercontent.com/12789366/103835910-6b70f180-50ec-11eb-85a6-7e4748490d0a.png)

from the source code i can see there is a support for this  but naming is wrong .

![image](https://user-images.githubusercontent.com/12789366/103836004-9fe4ad80-50ec-11eb-9a0c-3160a55234f7.png)

Therefore when we map algorithm by name it throws an exception : 

![image](https://user-images.githubusercontent.com/12789366/103836056-c571b700-50ec-11eb-8a26-a38251bf4159.png)

The potential fix is to tweak a naming :

![image](https://user-images.githubusercontent.com/12789366/103836092-e6d2a300-50ec-11eb-9a47-d348db35a387.png)

**Comment by rbellens** [comment]
fixed in version `0.3.0-nullsafety.2`
