### ISSUE TITLE
ES256 Header format

### ISSUE THREAD

**Issue by nicolasgarnet** [appsup-dart/jose#21]
Hi,

I am just diving in this package by trying to create a [ES256 JWT for GCP IoT Core](https://cloud.google.com/iot/docs/how-tos/credentials/jwts) :

I see how to build claims with JsonWebTokenClaims and signature with addRecipient, if I'm not mistaken, but I don't really get the way to build my headers.

How do you do it ?

**Comment by rbellens** [comment]
For examples of creating a JWT, please see the example directory. E.g. example 7 here: https://github.com/appsup-dart/jose/blob/7f3d6c646ba5013edf413d99ad7be386ddaa8b6b/example/jose_example.dart#L264

The `alg` header value will be added automatically when you add a recipient with the required algorithm. The `typ` header value can be added by: 

```dart
builder.setProtectedHeader('typ', 'JWT');
```
