### ISSUE TITLE
base64url Encoded Secret and type property

### ISSUE THREAD

**Issue by sachaarbonel** [appsup-dart/jose#25]
Hi, thanks for this great library. I would like to suggest some improvements regarding the JWS builder and docs overall.
I had some issues first with setting the type properties `type`, I would suggest adding it to the JWT example or add a convenient method.
```dart
 builder.setProtectedHeader('typ', 'JWT');
```

I had also another issue with the secret. I see that there are some factory methods that automatically base64url encode some parameters of JsonWebKey. But in the JWT example, you pass in an already encoded secret.

```dart
builder.addRecipient(
        JsonWebKey.fromJson({
          'kty': 'oct',
          'k': base64Urlencode(secret),
        }),
        algorithm: 'HS256');
``` 

```dart
String base64Urlencode(String secret) {
  Codec<String, String> stringToBase64Url = utf8.fuse(base64Url);
  String encoded = stringToBase64Url.encode(secret);
  return encoded;
}
```

**Comment by lelabo-marc** [comment]
I fell in this trap. I had to dig a bit to understand why I was getting error while decoding a JWE token created with python.

**Comment by rbellens** [comment]
Thanks for the suggestions. These are now added to the examples.
