### ISSUE TITLE
Signing JWT with RS512

### ISSUE THREAD

**Issue by coylums** [appsup-dart/jose#3]
Hello, I'm working with Jose and trying to sign a JWT with RS512, a requirement from an API I'm using. When I attempt to include the `RS512` algorithm I get `type 'RSASigner' is not a subtype of type 'Mac'` with the *Create a JWS* example. I don't know if this is an issue with the package or how I'm trying to use RS512. Thank you.

**Comment by joaoritter** [comment]
+1 for RSA256.

**Comment by mdevalk** [comment]
Hi @coylums, any news on this? Did you get it resolved?

**Comment by jerrywell** [comment]
FYI, RS256 works for me.

**Comment by ljbdelacruz** [comment]
hi any news on this? still having issues with JWT :( same error

**Comment by rbellens** [comment]
You'll first need a key to do the signing. Depending on the application, you'll need to use a key that is provided to you or you can generate one for example with the following openssl command:

```sh
ssh-keygen -t rsa -b 4096 -m PEM -f jwtRS512.key
```

Next, you'll need to parse the key and transform it to a `JsonWebKey` object. Depending on the format the key is stored in, you'll need to use the appropriate library. For example, for keys stored in `pem` format, you can use the package `x509`.

Finally, you can use this `JsonWebKey` for signing a jwt.

See example7 in the examples file for a full example.

https://github.com/appsup-dart/jose/blob/6b3eb03694bfac7d4d1d50dda83c98802d340033/example/jose_example.dart#L264-L317
