### ISSUE TITLE
Using pem certificate for verification?

### ISSUE THREAD

**Issue by ab36245** [appsup-dart/jose#30]
I'm trying to validate a Firebase generated token using jose. It looks ideal for what I'm trying to do. Following the instructions  [here](https://firebase.google.com/docs/auth/admin/verify-id-tokens#verify_id_tokens_using_a_third-party_jwt_library) I  can source public keys for verification from [https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com](). This is not a web key set (per RFC 7517) but rather a simple JSON map of ids and pems. That's fine, I'm happy to fetch these myself and load each into a `JsonWebKeyStore`.

The problem is that each pem is a certificate, not a public key. When I call `JsonWebKey.fromPem` the library throws a `FormatException` (could not parse PEM).

If I manually extract the public key from the certificate (using openssl command line) `JsonWebKey.fromPem` works fine.

Should handling certificate pems work? If not, how can I extract the public key? (Ideally Google would provide a web key set for this but if they don't I'm going to be stuck).

**Comment by rbellens** [comment]
I've updated the `JsonWebKey.fromPem` method to accept certificate pems as well. Will be released soon.

**Comment by ab36245** [comment]
Thanks @rbellens
