### ISSUE TITLE
UnimplementedError: Cannot handle netscape-comment (netscape-cert-extension 13))

### ISSUE THREAD

**Issue by joselicht90** [appsup-dart/jose#36]
Hi, I'm trying to validate a JWT that is sign with RSA256 and when y try to create a keystore from pem i get this error

UnimplementedError (UnimplementedError: Cannot handle netscape-comment (netscape-cert-extension 13))

This is my code
// create a JsonWebSignature from the encoded string
var _jws = JsonWebSignature.fromCompactSerialization(_jwtRaw);
var _keyStore = new JsonWebKeyStore()..addKey(JsonWebKey.fromPem(_cp));
await _jws.verify(_keyStore);

**Comment by rbellens** [comment]
I guess this is an issue with the `x509` package that handles the parsing of the pem file. Please, post an issue there. I will close it here.
