### ISSUE TITLE
Json Web Encryption requires header field to be present

### ISSUE THREAD

**Issue by siemtim-dev** [appsup-dart/jose#41]
I am using the Version 0.3.2 of this package. The constructor `JsonWebEncryption.fromJson(Map<String, dynamic> json)` requires the unprotected header field to be present, but per RFC 7516 the header field must be absent if it is empty.

If there is only one recipient, this package seems to use the flatterned JWE JSON serialisation syntax. Here the package requires the `header` field to be present in the to level object, but this fiels must be absent if it is empty according to the specification. 

The error occured while making direct use of a shared symmetric key as the CEK.

**Comment by rbellens** [comment]
Should be fixed with pull request #43.
Will be merged in next release.
