### ISSUE TITLE
is there a plan to remove `@visibleForTesting` for generateCryptoKeyPair in class JsonWebAlgorithm?

### ISSUE THREAD

**Issue by luojiakickoff** [appsup-dart/jose#45]
Hello,
i am tring to generate an keypair with 'ES256', and i made it by using the `generateCryptoKeyPair()` method in class JsonWebAlgorithm.
but right now the method is directed by `@visibleForTesting` directive, which resulting for noticing that i can only use it in a test.

will you consider to remove the `@visibleForTesting` , or is there any other method for this package to generate the keypairs with 'EC256'?

**Comment by rbellens** [comment]
You can use the `generateRandomKey` method from the  `JsonWebAlgorithm` class. This will generate a `JsonWebKey`. The getter `cryptoKeyPair` gives you access to the key pair.
