### ISSUE TITLE
This JsonWebKey does not support the 'wrapKey' operation 

### ISSUE THREAD

**Issue by Marcusjvr** [appsup-dart/jose#46]
I am using jose because of a requirement, I am using the `RSA-OAEP-256` algorithm and the `A256CBC-HS512` encryption, the jwk I am using is a json so I use the method `final key = JsonWebKey.fromJson(textKey)` to get the `jsonWebKey`.

When I use the `_builder.build()` method I get an error `This JsonWebKey does not support the 'wrapKey' operation`.  
The code is below 
`    _builder.stringContent = content;

    final key = JsonWebKey.fromJson(textKey);

    _builder.addRecipient(key, algorithm: 'RSA-OAEP-256');
    _builder.encryptionAlgorithm = 'A256CBC-HS512';

    final jwe = _builder.build();
    return jwe.toCompactSerialization();`

Please what exactly am I doing wrong?

**Comment by rbellens** [comment]
Check out `example4` in `example/jose_example.dart`. When you replace the algorithms there with the ones you use, this seems to work fine. 
Possibly, you are using a jwk of the wrong type. It should be RSA, I believe
