### ISSUE TITLE
X.509 keys support

### ISSUE THREAD

**Issue by SebAubin** [appsup-dart/jose#6]
Hi, is there any updates on the support of X.509 keys?

**Comment by KouloukLeGrand** [comment]
Hi @SebAubin! Has your problem been solved, or did you find an alternative for verifying JWT?

**Comment by SebAubin** [comment]
Unfortunately no.

**Comment by rbellens** [comment]
See the `x509` package for parsing keys.

Also see this example:

https://github.com/appsup-dart/jose/blob/6b3eb03694bfac7d4d1d50dda83c98802d340033/example/jose_example.dart#L264-L317
