### ISSUE TITLE
JWE RSA-OAEP-256

### ISSUE THREAD

**Issue by ljbdelacruz** [appsup-dart/jose#8]
having hard time finding equivalent of this code from swift to flutter 

SWIFT: 
var header = JWEHeader(algorithm: .RSAOAEP256, encryptionAlgorithm: .A128CBCHS256)
        header.kid = "2018-10-08"
        header.typ = "JWE"
        let encrypter = Encrypter(keyEncryptionAlgorithm: .RSAOAEP256, encryptionKey: publicKey, contentEncyptionAlgorithm: .A128CBCHS256)!
let payload = Payload(data);

guard let jwe = try? JWE(header: header, payload: payload, encrypter: encrypter) else {
            return ["message":""]
        }
return ["message":jwe.compactSerializedString];

FLutter when implementing RSA-OAEP 256:
Error: Algorithm not implemented 

please help me out thanks

**Comment by rbellens** [comment]
RSA-OAEP is now implemented (version 0.2.0)
